gui:
  language: 'en'
customCommands:
  - key: "C"
    description: "AIでコミットメッセージを生成"
    command: "czg ai"
    context: "files"
    output: terminal
  - key: "<c-f>"
    description: "git pull --rebase --autostash"
    command: "git pull --rebase"
    context: "localBranches"
    output: log
