customCommands:
  - key: "C"
    description: "AIでコミットメッセージを生成"
    command: "czg ai"
    context: "files"
    subprocess: true
  - key: "<c-f>"
    description: "git pull --rebase --autostash"
    command: "git pull --rebase"
    context: "localBranches"
    stream: true
