[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# Develop environment for vim plugin
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'easymotion/vim-easymotion'
# s{char} to move to {char}{char}
hook_add = '''
  nmap s <Plug>(easymotion-s2)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0rp/ale'
# Ctrl + kで次の指摘へ、Ctrl + jで前の指摘へ移動
hook_add = '''
  let g:ale_lint_on_enter = 0
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = 'open /Applications/Google\ Chrome.app'
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
rev = '01203d4c9'

[[plugins]]
# Markdown Preview
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app && yarn install'

[[plugins]]
# Syntax highlight toml
repo = 'cespare/vim-toml'

[[plugins]]
# Color scheme
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:solarized_termcolors=256
'''

[[plugins]]
# Color scheme
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  let g:solarized_termcolors=256
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-lsp']
